# ==== General Configuration ====
# Documentation of the TOML format: https://toml.io/en/latest

# Allow only a single vocabulary (default) or multiple vocabularies in the repository.
single_vocab = true

# == eLTER Data Level code list derived from https://elter.atlassian.net/wiki/spaces/EC/pages/918749186/eLTER+Data+Levels ==
[vocabs.dataLevel]
id_length = 2
permanent_iri_part = "https://vocabs.lter-europe.net/dataLevel/" # may be to be changed with new URI of eLTER vocabularies!
[vocabs.dataLevel.checks]
allow_delete = false
[vocabs.dataLevel.prefix_map]
elter_dl = "https://vocabs.lter-europe.net/dataLevel" # ???
[[vocabs.dataLevel.id_range]]
first_id = 1
last_id = 10
gh_name = "oggioniale"
orcid = "0000-0002-7997-219X"
ror_id = "https://ror.org/02wxw4x45"
